//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace UserRegisteration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class postnr
    {
        public int ID { get; set; }

      
        public string ZipCity { get; set; }

        [Required(ErrorMessage = "This filed has to be filled.")]
        public string ZipCode { get; set; }
    }
}
